In [5]:
import numpy as np  
import matplotlib.pyplot as plt


pc_rates=[0]
type(pc_rates)


list

In [25]:
x=[np.zeros(10),np.zeros(10)+1,np.zeros(10)+2]
y=[np.zeros(10),np.zeros(10)+1,np.zeros(10)+2]
z=np.append(x,y,axis=0)
print(z.transpose())


[[0. 1. 2. 0. 1. 2.]
 [0. 1. 2. 0. 1. 2.]
 [0. 1. 2. 0. 1. 2.]
 [0. 1. 2. 0. 1. 2.]
 [0. 1. 2. 0. 1. 2.]
 [0. 1. 2. 0. 1. 2.]
 [0. 1. 2. 0. 1. 2.]
 [0. 1. 2. 0. 1. 2.]
 [0. 1. 2. 0. 1. 2.]
 [0. 1. 2. 0. 1. 2.]]


In [3]:
nvn=10
X=[i for i in range(nvn)]*3
print(X)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [9]:
spike_times=np.load('spike_times.npy',allow_pickle=True)
print(spike_times[0])

[8.900000e-05 1.425600e-02 2.828400e-02 4.231200e-02 5.634000e-02
 7.036800e-02 8.439600e-02 9.842400e-02 1.124650e-01 1.265030e-01
 1.425150e-01 1.585650e-01 1.765780e-01 1.946130e-01 2.126490e-01
 2.306850e-01 2.487210e-01 2.667570e-01 2.847930e-01 3.028290e-01
 3.208660e-01 3.389010e-01 3.569380e-01 3.749730e-01 3.930090e-01
 4.110460e-01 4.290820e-01 4.471180e-01 4.651540e-01 4.831910e-01
 5.012270e-01 5.192700e-01 5.372980e-01 5.553400e-01 5.733700e-01
 5.914060e-01 6.094420e-01 6.274790e-01 6.455210e-01 6.635500e-01
 6.815860e-01 6.996230e-01 7.176640e-01 7.356950e-01 7.537320e-01
 7.717680e-01 7.898030e-01 8.078390e-01 8.258760e-01 8.439120e-01
 8.619470e-01 8.799830e-01 8.980250e-01 9.160550e-01 9.340920e-01
 9.521280e-01 9.701640e-01 1.974190e+00 1.988206e+00 2.002233e+00
 2.016261e+00 2.030288e+00 2.044318e+00 2.058355e+00 2.072372e+00
 2.086403e+00 2.100450e+00 2.116463e+00 2.132514e+00 2.150533e+00
 2.168561e+00 2.186597e+00 2.204638e+00 2.222670e+00 2.240706e+00
 2.258742e