In [17]:
import numpy as np  
import matplotlib.pyplot as plt


pc_rates=[0]

type(pc_rates)


list

In [25]:
x=[np.zeros(10),np.zeros(10)+1,np.zeros(10)+2]
y=[np.zeros(10),np.zeros(10)+1,np.zeros(10)+2]
z=np.append(x,y,axis=0)
print(z.transpose())


[[0. 1. 2. 0. 1. 2.]
 [0. 1. 2. 0. 1. 2.]
 [0. 1. 2. 0. 1. 2.]
 [0. 1. 2. 0. 1. 2.]
 [0. 1. 2. 0. 1. 2.]
 [0. 1. 2. 0. 1. 2.]
 [0. 1. 2. 0. 1. 2.]
 [0. 1. 2. 0. 1. 2.]
 [0. 1. 2. 0. 1. 2.]
 [0. 1. 2. 0. 1. 2.]]


Docstring:
arange([start,] stop[, step,], dtype=None, *, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The interva

In [3]:
nvn=10
X=[i for i in range(nvn)]*3
print(X)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [9]:
spike_times=np.load('spike_times.npy',allow_pickle=True)
print(spike_times[0])

[8.900000e-05 1.425600e-02 2.828400e-02 4.231200e-02 5.634000e-02
 7.036800e-02 8.439600e-02 9.842400e-02 1.124650e-01 1.265030e-01
 1.425150e-01 1.585650e-01 1.765780e-01 1.946130e-01 2.126490e-01
 2.306850e-01 2.487210e-01 2.667570e-01 2.847930e-01 3.028290e-01
 3.208660e-01 3.389010e-01 3.569380e-01 3.749730e-01 3.930090e-01
 4.110460e-01 4.290820e-01 4.471180e-01 4.651540e-01 4.831910e-01
 5.012270e-01 5.192700e-01 5.372980e-01 5.553400e-01 5.733700e-01
 5.914060e-01 6.094420e-01 6.274790e-01 6.455210e-01 6.635500e-01
 6.815860e-01 6.996230e-01 7.176640e-01 7.356950e-01 7.537320e-01
 7.717680e-01 7.898030e-01 8.078390e-01 8.258760e-01 8.439120e-01
 8.619470e-01 8.799830e-01 8.980250e-01 9.160550e-01 9.340920e-01
 9.521280e-01 9.701640e-01 1.974190e+00 1.988206e+00 2.002233e+00
 2.016261e+00 2.030288e+00 2.044318e+00 2.058355e+00 2.072372e+00
 2.086403e+00 2.100450e+00 2.116463e+00 2.132514e+00 2.150533e+00
 2.168561e+00 2.186597e+00 2.204638e+00 2.222670e+00 2.240706e+00
 2.258742e

In [2]:
from itertools import product

param_grid = {
    'SST_W0': product([2,3],[10,50,100]),
    'SST_W1': product([4],[10,50,100,200]),
    'SST_AMPA_GAIN': product([1,2], [10,100,150]),
    'SST_AMPA_TAU': product([0], [10,100,150]),
    'SST_LEAK': product([0], [10,20,30,100]),
    'Input_SST': [.2],
    'PC_SST': [.1]
}

# Flatten the product for the first four parameters
expanded_param_grid = {
    key: list(value) for key, value in param_grid.items()
}
param_values = list(expanded_param_grid.values())
total_combinations = len(list(product(*param_values))) #

In [4]:
print(expanded_param_grid)
print(total_combinations)

{'SST_W0': [(2, 10), (2, 50), (2, 100), (3, 10), (3, 50), (3, 100)], 'SST_W1': [(4, 10), (4, 50), (4, 100), (4, 200)], 'SST_AMPA_GAIN': [(1, 10), (1, 100), (1, 150), (2, 10), (2, 100), (2, 150)], 'SST_AMPA_TAU': [(0, 10), (0, 100), (0, 150)], 'SST_LEAK': [(0, 10), (0, 20), (0, 30), (0, 100)], 'Input_SST': [0.2], 'PC_SST': [0.1]}
1728


In [5]:
print(param_values)

[[(2, 10), (2, 50), (2, 100), (3, 10), (3, 50), (3, 100)], [(4, 10), (4, 50), (4, 100), (4, 200)], [(1, 10), (1, 100), (1, 150), (2, 10), (2, 100), (2, 150)], [(0, 10), (0, 100), (0, 150)], [(0, 10), (0, 20), (0, 30), (0, 100)], [0.2], [0.1]]


In [14]:
import pickle
try:
    with open('results_2.pkl', 'rb') as f:
        results = pickle.load(f)
except FileNotFoundError:
    results = []


for i in results:
    print(i)
    

({'SST_W0': (2, 10), 'SST_W1': (4, 10), 'SST_AMPA_GAIN': (1, 10), 'SST_AMPA_TAU': (0, 10), 'SST_LEAK': (0, 10), 'Input_SST': 0.2, 'PC_SST': 0.1}, 0.0)
({'SST_W0': (2, 10), 'SST_W1': (4, 10), 'SST_AMPA_GAIN': (1, 10), 'SST_AMPA_TAU': (0, 10), 'SST_LEAK': (0, 20), 'Input_SST': 0.2, 'PC_SST': 0.1}, 0.0)
({'SST_W0': (2, 10), 'SST_W1': (4, 10), 'SST_AMPA_GAIN': (1, 10), 'SST_AMPA_TAU': (0, 10), 'SST_LEAK': (0, 30), 'Input_SST': 0.2, 'PC_SST': 0.1}, 0.0)
({'SST_W0': (2, 10), 'SST_W1': (4, 10), 'SST_AMPA_GAIN': (1, 10), 'SST_AMPA_TAU': (0, 10), 'SST_LEAK': (0, 100), 'Input_SST': 0.2, 'PC_SST': 0.1}, 0.0)
({'SST_W0': (2, 10), 'SST_W1': (4, 10), 'SST_AMPA_GAIN': (1, 10), 'SST_AMPA_TAU': (0, 100), 'SST_LEAK': (0, 10), 'Input_SST': 0.2, 'PC_SST': 0.1}, 0.0)
({'SST_W0': (2, 10), 'SST_W1': (4, 10), 'SST_AMPA_GAIN': (1, 10), 'SST_AMPA_TAU': (0, 100), 'SST_LEAK': (0, 20), 'Input_SST': 0.2, 'PC_SST': 0.1}, 0.0)
({'SST_W0': (2, 10), 'SST_W1': (4, 10), 'SST_AMPA_GAIN': (1, 10), 'SST_AMPA_TAU': (0, 100),

In [11]:
type(results)
print

list

In [15]:
list(product([0][10,20]))

<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
/tmp/ipykernel_40498/3590314543.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  list(product([0][10,20]))
/tmp/ipykernel_40498/3590314543.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  list(product([0][10,20]))
/tmp/ipykernel_40498/3590314543.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  list(product([0][10,20]))


TypeError: list indices must be integers or slices, not tuple

In [26]:
import numpy as np
from itertools import product

param_grid = {
    'SST_W0': product([3,4],[10,50,100]),
    'SST_AMPA_GAIN': product([2,3], [10,100,150]),
    'SST_AMPA_TAU': product([1, 0], [10,100,150]),
    'SST_LEAK': product([0], [10,20,250]),
    'Input_SST': [.05, .1,.2],
    'PC_SST': [.05, .1,.2]
}

# Flatten the product for the parameters
expanded_param_grid = {
    key: list(value) for key, value in param_grid.items()
}

param_values = list(expanded_param_grid.values())

print(param_values)



[[(3, 10), (3, 50), (3, 100), (4, 10), (4, 50), (4, 100)], [(2, 10), (2, 100), (2, 150), (3, 10), (3, 100), (3, 150)], [(1, 10), (1, 100), (1, 150), (0, 10), (0, 100), (0, 150)], [(0, 10), (0, 20), (0, 250)], [0.05, 0.1, 0.2], [0.05, 0.1, 0.2]]


In [ ]:
# Load previous results if available
excel_file = 'results_1.xlsx'
if os.path.exists(excel_file):
    results_df = pd.read_excel(excel_file)
else:
    results_df = pd.DataFrame()

In [23]:

# Iterate through the parameter grid
for params in product(*param_values):
    current_params = {
        key: (item[0], item[1]) if isinstance(item, tuple) else item
        for key, item in zip(expanded_param_grid.keys(), params)
    }

    # Check if current_params already exists in results_df
    if not results_df.empty and (results_df[list(current_params.keys())] == pd.Series(current_params)).all(axis=1).any():
        continue  # Skip already completed simulations

    print(f"Running simulation with parameters: {current_params}...")
    # Update the values in neuron_config with the current parameter values
    neuron_config.update(current_params)

    try:
        [output_events, test_config] = run_simulation(neuron_config)
        fot_output= frequency_over_time(test_config, output_events)
        [time_axis, ff_windows_pc, ff_windows_pv, ff_windows_sst] = fot_output
        fvt_fig = frequency_vs_time_plot(frequency_over_time(test_config, output_events), test_config, save=True, annotate=True,neuron_config=neuron_config)
        slope = calculate_slope(time_axis, ff_windows_sst)
        results.append((current_params, slope))  # Storing the current_params instead of neuron_config
        # Save progress
        with open('results_1.pkl', 'wb') as f:
            results.append((current_params, slope))  # Storing the current_params instead of neuron_config
            pickle.dump(results, f)
    except timeout_decorator.TimeoutError:
        print("Simulation timed out, trying again with new parameters...")


print("Simulation completed")



[]
[]
[]
[]
[0.05, 0.1, 0.2]
[0.05, 0.1, 0.2]
